### ISSUE TITLE
Please update Ubuntu package

### ISSUE THREAD

**Issue by rrthomas** [tarickb/sasl-xoauth2#20]
The Ubuntu package does not currently have the SSF fix.

**Comment by rrthomas** [comment]
Thanks for rapidly merging all my recent PRs! Is there anything I can do to help with this issue? It would be great to be able to use the Ubuntu package again.

**Comment by tarickb** [comment]
Done:

https://launchpad.net/~sasl-xoauth2/+archive/ubuntu/stable/+packages
