### ISSUE TITLE
Simplify Debian & Ubuntu packaging

### ISSUE THREAD

**Issue by rrthomas** [tarickb/sasl-xoauth2#26]
Could the project just have a single version of the packaging committed, compatible with current Debian stable and current Ubuntu LTS? If so, the focal packaging would be a good place to start. I see this was the only version updated anyway recently when a new release was made.

(Also I note that `compat` is wrong for focal: says `9`, should say `11`; I'll fix that!)

**Comment by tarickb** [comment]
To be honest I know very little about how packaging *ought* to be done, and so my strategy has been to do more or less the minimum necessary to have Launchpad accept the output. :) Please feel free to take a stab at it if you want to though.

**Comment by rrthomas** [comment]
Fair enough; I'm a Debian Maintainer (that's apprentice Debian Developer), so I'm fairly well up on Debian packaging. I'll give it a go.
