### ISSUE TITLE
support for ubuntu 22.04

### ISSUE THREAD

**Issue by bigalownz** [tarickb/sasl-xoauth2#36]
support for ubuntu 22.04 (Jammy) needed in
https://launchpad.net/~sasl-xoauth2/+archive/ubuntu/stable

**Comment by tarickb** [comment]
Sorry for the delay here -- I published an updated package for 22.04 last month:

https://launchpad.net/~sasl-xoauth2/+archive/ubuntu/stable/+sourcepub/13874871/+listing-archive-extra
