### ISSUE TITLE
support for centos7

### ISSUE THREAD

**Issue by vadimprt** [tarickb/sasl-xoauth2#37]

**Comment by vadimprt** [comment]
unable to building from source on centos7:

CMake Error at CMakeLists.txt:15 (cmake_minimum_required):
  CMake 3.0.0 or higher is required.  You are running version 2.8.12.2


-- Configuring incomplete, errors occurred!
See also "/tmp/sasl-xoauth2/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/sasl-xoauth2/build/CMakeFiles/CMakeError.log".

**Comment by tarickb** [comment]
That seems like a pretty old version of CMake, I'm not sure how feasible it is to try to support it...

**Comment by Jakuje** [comment]
I have epel7 built package here: https://copr.fedorainfracloud.org/coprs/jjelen/sasl-xoauth2/

**Comment by tarickb** [comment]
Thanks @Jakuje!
