### ISSUE TITLE
TokenStore::Read: failed to open file

### ISSUE THREAD

**Issue by averter** [tarickb/sasl-xoauth2#38]
I am trying to use this sasl-xoauth2 plugin together with [oauth2ms](https://github.com/harishkrupo/oauth2ms) as described [here](https://github.com/harishkrupo/oauth2ms/blob/main/steps.org). In doing so it is assumed that installing sasl-xoauth2 or cyrus-sasl-xoauth2 is the same.
As reported in [this issue](https://github.com/harishkrupo/oauth2ms/issues/9) by checking `/var/log/syslog` the sasl-xoauth2 plugin is giving this error:

```
mypcname sasl-xoauth2: auth failed: 2022-07-24 18:05:22: TokenStore::Read: failed to open file <<my token>>
```
which suggests that sasl-xoauth2 is waiting for a file from oauth2ms? Any help in solving this issue is very welcome.

**Comment by tarickb** [comment]
sasl-xoauth2 and cyrus-sasl-xoauth2 are not the same, no. Please make sure you've followed the instructions in the [sasl-xoauth2 README](https://github.com/tarickb/sasl-xoauth2/blob/master/README.md).

**Comment by averter** [comment]
Thanks @tarickb. After a lot of trial and error I was able to get cyrus-sasl-xoauth2 up and running — finally!

**Comment by kunliugithub** [comment]
> Thanks @tarickb. After a lot of trial and error I was able to get cyrus-sasl-xoauth2 up and running — finally!

@averter I am facing the exact same issue you are describing here. Could you please let me know how you resolved it? Thanks.

**Comment by tarickb** [comment]
Please look through the [debugging section of the README](https://github.com/tarickb/sasl-xoauth2#debugging) and attach logs (with credentials redacted).
