### ISSUE TITLE
Would it be possible (or is it necesary) to make the tokenEndpoint configurable?

### ISSUE THREAD

**Issue by tparkercbn** [tarickb/sasl-xoauth2#4]
I would like to use this plugin with postfix and Office365 and the token endpoint seems to be google specific.  

Microsoft uses: https://login.microsoftonline.com/{ tenant ID }/oauth2/token where tenant id would be for the app you have registered on azure active directory.

I am going to try to patch the code and if I can make this a configuration Item I will submit a pull request but I am not a C programmer and am not sure if I will be sucessful.  

Is this a change you would be willing to make?

Tom

**Comment by tarickb** [comment]
Updated the README with instructions on using Outlook/Office 365. Thanks Tom and Karl for helping figure this out!
