### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by dgslos** [tarickb/sasl-xoauth2#40]
I tried to run sasl-xoauth2-token-tool, but all I get is 'command not found'. I installed it following the instructions with apt-get. What I'm I doing wrong? Are the binaries not added to the path?

**Comment by tarickb** [comment]
Can you share a little more about your environment (which Ubuntu release, which version of sasl-xoauth2, etc.)?

**Comment by dgslos** [comment]
Yes, sorry, forgot to mention.
OS: Ubuntu 20.04.4 LTS
Sasl-xoath2 version: 0.12-1ubuntu1~focal1~ppa1

**Comment by tarickb** [comment]
Ah yeah, looks like we've not released anything for 20.04 in a while. I'll work on getting a new version pushed out.

**Comment by funilrys** [comment]
@tarickb I'm a "hardcore" _(as my colleagues say 😄)_ / longtime Linux user and I know how to handle this but in my setup, I always do a `chmod +x` after `make install`. This is a real issue when building from a source.

**Comment by tarickb** [comment]
@dgslos I pushed a new version for 20.04 earlier today. Want to give that a try?
