### ISSUE TITLE
Documentation for adding API permissions

### ISSUE THREAD

**Issue by whitemice** [tarickb/sasl-xoauth2#45]
The instructions "add API permissions for SMTP.Send" .... it appears that SMTP.Send has moved?  Two people have been unable to find this under "API Permission" after creating a native client app registration

**Comment by ImAnOwl** [comment]
Got the same problem, but you have to register it as delegated permission, then you will find it :)

**Comment by tarickb** [comment]
From the app registration "API permissions" page, click "add a permission", then "Microsoft Graph", and from there enter "SMTP.Send" in the search box. If you then expand the "SMTP" permission, you should see a checkbox for "SMTP.Send". Is that not the case?

**Comment by whitemice** [comment]
Yep, found it (I believe)
_Application_ -> View API Permissions -> Add a permission -> Microsoft Graph -> Delegated Permissions -> Search "SMTP" -> SMTP.Send **checked**
