### ISSUE TITLE
Problem with Token on Ubuntu

### ISSUE THREAD

**Issue by Flobo1709** [tarickb/sasl-xoauth2#47]
Hi,

we followed your tutorial, with Office 365 and Ubuntu 22.04 LTS.
We fail at this point
sasl-xoauth2-token-tool get-token outlook --client-id=123ABC --tenant=DEG456

how do we have to set the command to write the output to the file? PATH_TO_TOKENS_FILE does not work for us, no matter which path we enter.

Can you please give me an example, thank you.

**Comment by tarickb** [comment]
Yeah it looks like the library sasl-xoauth2-token-tool uses to parse arguments is a little finicky. I tried this myself on Ubuntu 22.04 and the following should work:

```
sasl-xoauth2-token-tool get-token outlook /tmp/sasl-token.json --client-id="foo" --tenant="bar"
```

(In other words the filename has to appear before `--client-id`.)

I'll try to fix this in a future release.

**Comment by Flobo1709** [comment]
Thanks, that worked, unfortunately I have another error now 
When checking the token I get the following message

2022-10-06 16:23:37: TokenStore::Read: file=/etc/tokens/mail@provider.de.json
2022-10-06 16:23:37: TokenStore::Read: refresh=0., 
2022-10-06 16:23:37: TokenStore::Refresh: attempt 1
2022-10-06 16:23:37: TokenStore::Refresh: token_endpoint: https://login.microsoftonline.com/common/oauth2/nativeclient
2022-10-06 16:23:37: TokenStore::Refresh: Request: client_id=ebea86fd-fhGT9GYOcU16C
2022-10-06 16:23:37: TokenStore::Refresh: code=200, response=
2022-10-06 16:23:37: TokenStore::Refresh: exception=* row 1, column 1
  Syntax error: value, object or array expected.

Can you help me?

**Comment by tarickb** [comment]
Something looks wrong with the request that's being sent (`TokenStore::Refresh: Request: client_id=ebea86fd-fhGT9GYOcU16C`) -- did you truncate or otherwise modify that log line when you copied it here? Client IDs are UUIDs, as far as I can tell, and `ebea86fd-fhGT9GYOcU16C` doesn't look like a UUID to me. Please confirm that your token file (`/etc/tokens/mail@provider.de.json`) looks something like this:

```
{
    "access_token": "abcdef...",
    "refresh_token": "abcdef...",
    "expiry": 0
}
```

**Comment by tarickb** [comment]
I deleted your comment because in general you don't want to make your tokens or client IDs public.

What version of sasl-xoauth2 are you running? Did you build it yourself or are you using the binaries from the [PPA](https://launchpad.net/~sasl-xoauth2/+archive/ubuntu/stable/+packages)?

**Comment by Flobo1709** [comment]
Hi, we are using the binaries from PPA.
sasl-xoauth2                          0.17-1ubuntu1~jammy1~ppa1                    amd64        SASL extension for XOAUTH2

**Comment by tarickb** [comment]
There's certainly no need for payment or anything like that. Please email me (`tarick@bedeir.com`) the full logs from your most recent attempt to refresh your token, including the full command line you're using, and we'll take it from there.
