### ISSUE TITLE
sasl-xoauth2.conf question

### ISSUE THREAD

**Issue by phesster** [tarickb/sasl-xoauth2#51]
Once the tokens have been created and inserted into the JSON file for Postfix (eg: /etc/tokens/sender.tokens.json and /var/spool/postfix/etc/tokens/sender.tokens.json) does the sasl-xoauth2.conf file need to continue to contain the ClientSecret and/or the ClientID?

**Comment by tarickb** [comment]
Yes, the config file will need to continue to contain the client ID and secret, because they're used when refreshing tokens.

**Comment by phesster** [comment]
That's what I thought.  I think I'll crunch down the permissions on that file a bit, though.  Thanks for the response.
