### ISSUE TITLE
TokenStore::Read: fail to open file

### ISSUE THREAD

**Issue by kiurzz** [tarickb/sasl-xoauth2#52]
Hello, I have this issue:
![image](https://user-images.githubusercontent.com/56320554/198238658-0a29b050-6ac3-4f54-be2a-8c37e82c578a.png)

The file exist, I can read-it and there is the output of the sasl-xoauth2-test-config:
![image](https://user-images.githubusercontent.com/56320554/198238877-0c0ef804-b709-496a-9b38-1deeed555ff2.png)

Thanks for your help ;)

**Comment by tarickb** [comment]
Is it possible you have chroot enabled? The README has a [note](https://github.com/tarickb/sasl-xoauth2#a-note-on-chroot) that might be helpful.

**Comment by tarickb** [comment]
The [next section in the README](https://github.com/tarickb/sasl-xoauth2#ssltls-certificates) covers that topic. :) If that doesn't help, I'll need more information. What distribution/release are you using? What version of sasl-xoauth2? Did you build it yourself or are you using prebuilt binaries?

**Comment by tarickb** [comment]
Do you have `ca_bundle_file` or `ca_certs_dir` specified in `sasl-xoauth2.conf`? What's your TLS configuration in `/etc/postfix/main.cf`?

**Comment by tarickb** [comment]
Your config file specifies `smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt`, so it's interesting that that file doesn't make it into `/var/spool/postfix`. Can you verify that `/etc/ssl/certs/ca-certificates.crt` exists?

**Comment by tarickb** [comment]
Try coping it over manually?

**Comment by alfonsodou** [comment]
Hello,
I have the same problem. Here's the error message I get: 

TokenStore::Refresh: http error: SSL certificate problem: unable to get local issuer certificate 

In the directory /var/spool/postfix/etc/ssl/certs/ is the file ca-certificates.crt, copied from the folder /etc/ssl/certs/ 
In the configuration file /etc/saslxoauth2.conf the following parameter is defined: 
"ca_certs_dir": "/var/spool/postfix/etc/ssl/certs" 
I tried setting the parameter ca_bundle_file but the error is the same. 
Server has Debian GNU/Linux 10 (buster) installed 

Thanks for your support.

**Comment by tarickb** [comment]
Can you try unsetting `ca_certs_dir` and setting `ca_bundle_file` to `/etc/ssl/certs/ca-certificates.crt`? Note that I purposefully left out `/var/spool/postfix` from the path (because I suspect you have chroot enabled, and so the plugin will never see that part of the path). If that doesn't work please provide the same config-file snippets that I asked for above from @kiurzz.

**Comment by alfonsodou** [comment]
Ok, right. My mistake. Thank you.
This is the current content of the /etc/sasl-xoauth2.conf file

![image](https://user-images.githubusercontent.com/1931360/217467729-d4a1f9c1-12bd-40eb-8f77-baeb29499c1c.png)

And it works correctly, I get the tokens and they refresh automatically, but, I can't send the mails anyway. I always get the same error. This is the postfix log:

![image](https://user-images.githubusercontent.com/1931360/217467832-7bbb0e63-6067-47fa-b0a6-9c4be96fe000.png)

How do I know what is failing?
Thanks again.

**Comment by tarickb** [comment]
There aren't any sasl-xoauth2 traces in that log snippet, which leads me to believe that either 1) Postfix isn't successfully loading sasl-xoauth2 (in which case I'd suggest reviewing the [README](https://github.com/tarickb/sasl-xoauth2#configure-mail-agent)), or 2) sasl-xoauth2 is logging to `/var/log/syslog` but you sent me `/var/log/mail.log` (in which case, check `/var/log/syslog`).

**Comment by alfonsodou** [comment]
My apologies. It is now working properly. The problem I had is that at the time of obtaining the initial token I was identifying myself in O365 with a different user than the one configured in postfix for sending emails.
Thanks for your help and patience.

**Comment by tarickb** [comment]
Happy to help, and I'm glad you figured it out!
