### ISSUE TITLE
Support for Debian package?

### ISSUE THREAD

**Issue by mattsnowboard** [tarickb/sasl-xoauth2#53]
I wanted to use this on a stable Debian 11 machine and was hoping to use the package so I don't have to build from source/monitor this project for updates.

Unfortunately, I was not able to use the focal or jammy Ubuntu packages on Debian 11 as it seems focal uses an old libjsoncpp1 package and jammy uses a new libc6 and libjsoncpp25 package.

focal:
```
matt@srv2:~$ sudo apt-get update
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://security.debian.org/debian-security bullseye-security InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Get:4 https://ppa.launchpadcontent.net/sasl-xoauth2/stable/ubuntu focal InRelease [18.0 kB]
Get:5 https://ppa.launchpadcontent.net/sasl-xoauth2/stable/ubuntu focal/main Sources [744 B]
Get:6 https://ppa.launchpadcontent.net/sasl-xoauth2/stable/ubuntu focal/main amd64 Packages [548 B]
Get:7 https://ppa.launchpadcontent.net/sasl-xoauth2/stable/ubuntu focal/main Translation-en [172 B]
Fetched 19.5 kB in 4s (5,246 B/s)
Reading package lists... Done
matt@srv2:~$ sudo apt-get install sasl-xoauth2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 sasl-xoauth2 : Depends: libjsoncpp1 (>= 1.7.4) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

jammy:
```
matt@srv2:~$ sudo apt-get update
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://security.debian.org/debian-security bullseye-security InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Get:4 https://ppa.launchpadcontent.net/sasl-xoauth2/stable/ubuntu jammy InRelease [18.0 kB]
Get:5 https://ppa.launchpadcontent.net/sasl-xoauth2/stable/ubuntu jammy/main Sources [748 B]
Get:6 https://ppa.launchpadcontent.net/sasl-xoauth2/stable/ubuntu jammy/main amd64 Packages [552 B]
Get:7 https://ppa.launchpadcontent.net/sasl-xoauth2/stable/ubuntu jammy/main Translation-en [172 B]
Fetched 19.5 kB in 3s (6,873 B/s)
Reading package lists... Done
matt@srv2:~$ sudo apt-get install sasl-xoauth2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 sasl-xoauth2 : Depends: libc6 (>= 2.34) but 2.31-13+deb11u5 is to be installed
                Depends: libjsoncpp25 (>= 1.9.5) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Any plans to support a Debian stable package or some Ubuntu version that matches Debian stable (Bullseye), if such a version even exists?

**Comment by dkg** [comment]
Hi @mattsnowboard !  I've made an [experimental package](https://ftp-master.debian.org/new/sasl-xoauth2_0.19-1.html) which still has to clear debian's NEW queue.  When it gets out of NEW, if there is positive feedback on it, i'm happy to move it into unstable.  From there, anyone interested can backport it to debian stable using the https://backports.debian.org machinery.

When that becomes possible, I'd be happy to help with that if anyone is interested in such a backport.

**Comment by dkg** [comment]
it's in debian experimental now. i'd appreciate any testing folks can do, and feedback on it either in the debian BTS, or in bug reports here.

**Comment by minusdavid** [comment]
@tarickb Is there a better package to use for Debian? 

@dkg I was just about to try out the package you built. I am trying to get the Koha open source library management system using XOAUTH2 with Email::Sender::Transport::SMTP::Persistent via Authen::SASL and I think I know how to make it work, but I ran into some dependency issues on Debian 12 Bookworm:

```
 sasl-xoauth2 : Depends: libc6 (>= 2.38) but 2.36-9+deb12u8 is to be installed
                Depends: libcurl3t64-gnutls (>= 7.16.2) but it is not installable
                Depends: libjsoncpp26 (>= 1.9.6) but it is not installable
                Recommends: sasl-xoauth2-tool but it is not installable
```

I just tried downloading the .deb package off Debian and installing it, but got these errors. I thought it was a bit weird since https://packages.debian.org/experimental/sasl-xoauth2 says libcurl3-gnutls and libjsoncpp25 are (installable) dependencies. I was hoping I could just clarify the dependencies with you. Cheers!

**Comment by minusdavid** [comment]
Thanks, @tarickb. I'll give that a shot. 

Any chance of getting the "debian" directory added into this git repo? It would be cool to be able to easily build our own packages with a provided control file.

**Comment by tarickb** [comment]
It's here, it's just in a different [branch](https://github.com/tarickb/sasl-xoauth2/tree/packaging/ubuntu).

**Comment by minusdavid** [comment]
Oh awesome. Thanks, @tarickb .
