### ISSUE TITLE
please tag release 0.20

### ISSUE THREAD

**Issue by dkg** [tarickb/sasl-xoauth2#60]
It looks like 713f9b97ba3a5d0c085f4a6dc7379791822d4d09 is intended to be release 0.20 but there is no git tag for it.  if it is the release, could you put a public tag there?

(i don't know whether you have any scripted release process for this, but if you do, automatically pushing a public tag as the final stage of the process would be helpful to me as a downstream packager)

**Comment by tarickb** [comment]
It's not -- I was just updating the changelog for what will eventually be the 0.20 release. Is there a better way to do this that I'm not aware of?

**Comment by dkg** [comment]
On Sun 2023-03-26 12:19:43 -0700, tarickb wrote:
> Is there a better way to do this that I'm not aware of?

I usually update the changelog so that the heading of the unreleased
section says something like "changes in 0.20 [ not yet released ]"

and then when releasing, remove the bracketed annotation.

Alternately, if you don't want to commit to a subsequent version number,
you can start the heading with:

   "unreleased changes"

or

   "not yet released changes"

and then when releasing, revise the heading.

the third way to do this is to not update the changelog at all until
release, and ensure that your git commit comments are sufficiently clear
that you can use them to summarize the changes.  then the process of
release is to take the git commit comments and massage them into a
coherent story.

I know some projects auto-generate their release notes from their git
commits directly, but (a) i think that imposes unnecessary discipline on
the software development process: developers should write good git
commit comments, but shouldn't have to worry about how they read as
release notes entries, and (b) i think release notes should be
structured thematically to make them easier for a knowledgable human to
consume, and the themes of any given release aren't necessarily apparent
until all the commits are done.

      --dkg

**Comment by tarickb** [comment]
Autogenerating does appeal to me, but given the pretty low rate of change here I think I'm fine going with your suggestion. I stuck a `[NOT YET RELEASED]` at the top of the changelog.
