### ISSUE TITLE
`sasl-xoauth2-tool get-token` requires password, breaks some outlook token requests

### ISSUE THREAD

**Issue by jrollins** [tarickb/sasl-xoauth2#64]
Not all outlook token requests require a password, and in fact some will break (401 error) if a password is provided.

The recent commit to fix issue #62 modified `sasl-xoauth2-tool` to require a password for the `get-token` command, and always sends it in the initial token requests.  This breaks the request for users who don't require it.

I believe I can prepare an MR to fix the issue.

**Comment by tarickb** [comment]
Can you elaborate a little on *when* the client secret is required? Microsoft's docs are a little confusing on this point.

**Comment by tarickb** [comment]
If you're still having trouble with this issue, please try the device-flow option in sasl-xoauth 0.23. Full instructions are in the [README](https://github.com/tarickb/sasl-xoauth2/#outlookoffice-365-configuration-device-flow) but basically you need to enable "Allow public client flows" for your app registration (in the Azure console), and pass `--use-device-flow` to `sasl-xoauth2-tool`.
