### ISSUE TITLE
How to do multiple entries in /etc/sasl-xoauth2.conf, please?

### ISSUE THREAD

**Issue by scotto** [tarickb/sasl-xoauth2#79]

**Comment by tarickb** [comment]
Hey, thanks for opening this, and don't worry about it -- yours was a very legitimate question and I'd like to keep this issue around in case anyone else has a similar query. The mechanism for setting up multiple providers is described here:

https://github.com/tarickb/sasl-xoauth2#using-multiple-mail-providers-or-users-simultaneously

**Comment by scotto** [comment]
Thanks for making `sasl-xoauth2` and especially being ready to help so quickly!
