### ISSUE TITLE
Refesh O365 token when MFA is enabled

### ISSUE THREAD

**Issue by backloop-biz** [tarickb/sasl-xoauth2#83]
Hello, I'm using this plugin on my postfix relay but unfortunately when the session of the user that authorize the app expire the mail flow is stopped with this error:

Presented multi-factor authentication has expired due to policies configured by your administrator, you must refresh your multi-factor authentication to acces

I solve by re-auth manually but is there a way to avoid this and not block the relay every time the token/session expire?

**Comment by tarickb** [comment]
Yeah I don't know that there are great ways to address this ([example](https://github.com/microsoft/Partner-Center-PowerShell/issues/317)). As far as I can tell (and I'm not very familiar with Azure) this is a restriction configured by the domain (tenant?) administrator and there's not much sasl-xoauth2 can do about it.
