### ISSUE TITLE
Support for Ubuntu 24.04 (Noble Numbat)

### ISSUE THREAD

**Issue by bigalownz** [tarickb/sasl-xoauth2#84]
Support for Ubuntu 24.04 (Noble Numbat) needed for sasl-xoauth2

missing on 
https://launchpad.net/~sasl-xoauth2/+archive/ubuntu/stable

**Comment by tarickb** [comment]
Sorry for the delay here. I've got a build queued up here: https://launchpad.net/~sasl-xoauth2/+archive/ubuntu/stable/+build/28404893

**Comment by tarickb** [comment]
amd64 build is done, arm64 is still queued up. Details here: https://launchpad.net/~sasl-xoauth2/+archive/ubuntu/stable/+packages
