### ISSUE TITLE
problems with oracle linux 8 and postfix / xoauth2

### ISSUE THREAD

**Issue by danival36** [tarickb/sasl-xoauth2#88]
Hi!
We have two types of servers: some are Ubuntu (where Postfix / XOAUTH works perfectly and emails are sent successfully). And then we have Oracle Linux 8, where it works but I'm going crazy. The configuration is the same as on Ubuntu; I generate the token, refresh it, configure main.cf to point to the CA certificates, etc., but I get this error:

Jul 22 19:28:59 cloneprewblapps sasl-xoauth2[86363]: auth failed: 2024-07-22 19:28:59: TokenStore::Refresh: http error: error setting certificate verify locations:#012  CAfile: /var/spool/postfix/etc/ssl/certs/ca-bundle.crt#012  CApath: none

This file does exist:

[root@cloneprewblapps certs]# ls -lh ca-bundle.crt 
-r--r--r-- 1 root root 217K Jul 22 19:00 ca-bundle.crt

the other output of the error (the typical)
Jul 22 19:28:59 cloneprewblapps postfix/smtp[86366]: Read 220 chars: 250-smtp.gmail.com at your service, [84.
Jul 22 19:28:59 cloneprewblapps postfix/smtp[86366]: 995FF208767E: to=<xxxxx@upf.edu>, relay=smtp.gmail.com[64.233.184.108]:587, delay=14566, delays=14566/0.12/0.22/0, dsn=4.7.0, status=deferred (SASL authentication failed; cannot authenticate to server smtp.gmail.com[64.233.184.108]: bad protocol / cancel)

I've done the copy of cp /etc/ssl/certs/ca-certificates.crt /var/spool/postfix/etc/ssl/certs/ca-certificates.crt and I've check with curl that  ca-certificates.crt and ca-bundle.crt are ok. 

But this occurs when the validation is incorrect. Does anyone have any ideas? Thank you very much.

**Comment by tarickb** [comment]
Have you reviewed the [section on chroot in the README](https://github.com/tarickb/sasl-xoauth2?tab=readme-ov-file#a-note-on-chroot)? I think you may need to set `ca_bundle_file` in the sasl-xoauth2 config to `/etc/ssl/certs/ca-bundle.crt`.

**Comment by danival36** [comment]
You were right, 
finally I setted ca_bundle_file in the sasl-xoauth2 config pointing to /etc/ssl/certs/ca-certificates. 
Solved. 
Thanks a lot!

**Comment by tarickb** [comment]
Great, glad that worked.
