### ISSUE TITLE
Issue with Multiple Sender Addresses in Postfix using XOAUTH2

### ISSUE THREAD

**Issue by danival36** [tarickb/sasl-xoauth2#92]
Hi!
I have a Postfix server configured with XOAUTH, and everything works perfectly. However, I’ve noticed that now I can’t send emails with any other sender except the one specified in the saslpass file ([smtp.gmail.com]:587 user-xoauth@sample.com:/etc/tokens/user-xoauth@sample.com).

If I change the sender in the saslpass file, it doesn’t work. If I add multiple IDs in the sasl-xoauth2.conf file, only the first ID works (the second one doesn’t seem to exist).

What I want to do is something like this:

echo "mail 15" | mail -s "new mail from server @server1 with sender user1" -r "user1@sample.com" user3@sample.com

But when I do this, it always sends the email from user-xoauth@sample.com.

Is there any way to fix this?

Thanks!

**Comment by tarickb** [comment]
I'm not sure this is a sasl-xoauth2 issue. Have you configured [sender-dependent SASL authentication](https://www.postfix.org/SASL_README.html#client_sasl_sender) in Postfix?

**Comment by danival36** [comment]
Mmmm I think this is to configure diferent ISP providers. 
If, for example, I put this in the sasl_passwd file: 

[smtp.gmail.com]:587 user1.informatica@sample.edu:/etc/tokens/user1.informatica@sample.edu
[smtp.gmail.com]:587 user2.informatica@sample.edu:/etc/tokens/user2.informatica@sample.edu

is always sending from the first sender

the sender_dependent_relayhost_maps is enabled in postfix

Thanks!

**Comment by tarickb** [comment]
You can replace "ISP" with "Gmail" in the [Postfix docs](https://www.postfix.org/SASL_README.html#client_sasl_sender) and the effect will likely be what you want. I haven't tried this, but:

In `/etc/postfix/main.cf` (in addition to whatever you have already for SMTP TLS, etc.):

```
smtp_sender_dependent_authentication = yes
relayhost = [smtp.gmail.com]:587
sender_dependent_relayhost_maps = hash:/etc/postfix/sender_relay

smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
smtp_sasl_mechanism_filter = xoauth2
```

In `/etc/postfix/sasl_passwd`:

```
user1.informatica@sample.edu user1.informatica@sample.edu:/etc/tokens/user1.informatica@sample.edu
user2.informatica@sample.edu user2.informatica@sample.edu:/etc/tokens/user2.informatica@sample.edu
[smtp.gmail.com]:587 default.user@sample.edu:/etc/tokens/defailt.user@sample.edu
```

In `/etc/postfix/sender_relay`:

```
user1.informatica@sample.edu [smtp.gmail.com]:587
user2.informatica@sample.edu [smtp.gmail.com]:587
```

Don't forget to update the maps:

```
postmap /etc/postfix/sasl_passwd
postmap /etc/postfix/sender_relay
```

**Comment by danival36** [comment]
Bingo! It works perfectly! Thank you very much!
One last question: Can I use one token to send from more than one address?
For example, if I create a token with USER_A_@gmail.com, can I authorize the addresses of User B and C in Google Cloud Platform of User A to use the same token and send emails? Do you know if this is possible?
Thanks a lot!

**Comment by tarickb** [comment]
Great, glad it worked! As for sending with more than one address: I have no idea, but you might want to start [here](https://support.google.com/mail/answer/22370).
