### ISSUE TITLE
Postfix not connecting to personal Outlook account

### ISSUE THREAD

**Issue by ClearlyDazed** [tarickb/sasl-xoauth2#94]
I've done all the permutations possible, trying to have Postfix authenticate to Outlook account. I registered an app on Azure. I can run and get the token, but when I test and send an email from Postfix, the mail log shows: "Oct  6 15:40:22 Overlord postfix/smtp[2920786]: 01CE12225AA: SASL authentication failed; cannot authenticate to server smtp-mail.outlook.com[52.96.164.118]: generic failure". The syslog shows: "Oct  6 15:40:22 Overlord sasl-xoauth2[2920786]: auth failed:". I have also tried with smtp.office365.com server with the same results. Also with and without the client_secret. The Azure app is registered with Client Flow to YES and app permission with SMTP selected.

Chroot:
"# service type  private unpriv  chroot  wakeup  maxproc command + args
smtp      inet  n       -       y       -       -       smtpd
smtp      unix  -       -       y       -       -       smtp

Initial token:
sasl-xoauth2-tool get-token outlook \
    /etc/tokens/REDACTED@outlook.com \
    --client-id=DEDACTED \
    --use-device-flow 

Token permission:
total 4
-rw-r--r-- 1 postfix postfix 1656 Oct  6 09:48 REDACTED@outlook.com

The token is also saved to "/var/spool/postfix/etc/tokens"
The tests on the config and token refresh succeed.
Used the postmap and postfix restart

The sasl-xoauth2.conf:
{
  "client_id": "DEDACTED",
  "client_secret": "",
  "token_endpoint": "https://login.microsoftonline.com/consumers/oauth2/v2.0/token",
  "log_to_syslog_on_failure": "yes",
  "log_full_trace_on_failure": "yes"
}

Is there something wrong with the postfix main.cf?

"# See /usr/share/postfix/main.cf.dist for a commented, more complete version

"# Debian specific:  Specifying a file name will cause the first
"# line of that file to be used as the name.  The Debian default
"# is /etc/mailname.
"#myorigin = /etc/mailname

smtpd_banner = $myhostname ESMTP $mail_name (Ubuntu)
biff = no

"# appending .domain is the MUA's job.
append_dot_mydomain = no

"# Uncomment the next line to generate "delayed mail" warnings
"#delay_warning_time = 4h

readme_directory = no

"# See http://www.postfix.org/COMPATIBILITY_README.html -- default to 2 on
"# fresh installs.
compatibility_level = 3.6

"# TLS parameters
smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
smtpd_use_tls=yes
smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache

"# See /usr/share/doc/postfix/TLS_README.gz in the postfix-doc package for
"# information on enabling SSL in the smtp client.

smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
myhostname = Overlord.wp.shawcable.net
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
mydestination = Overlord.wp.shawcable.net, Overlord, localhost.localdomain, localhost

#stmp server for sending mail							 
relayhost = [smtp-mail.outlook.com]:587

#mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
mynetworks = 127.0.0.0/8
mailbox_size_limit = 51200000
recipient_delimiter = +
inet_interfaces = all
inet_protocols = ipv4

#stmp settings to send mail

default_transport = smtp
relay_transport = smtp

smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = hash:/etc/postfix/sasl/sasl_passwd
smtp_sasl_security_options =
smtp_tls_security_level = encrypt
smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt

#for oauth2
smtp_sasl_mechanism_filter = xoauth2
#relayhost = [smtp.office365.com]:587

Has something change with the Azure options?
Help with any suggestions to get this working is appreciated.

**Comment by tarickb** [comment]
Can you include the lines in the syslog after "auth failed:"? Assuming Postfix is actually using sasl-xoauth2, there should be a lot more logging information after that.

**Comment by ClearlyDazed** [comment]
Sorry for the delay. I ran another setup as above for outlook server smtp.office365.com and with tenant=consumers on a All Microsoft Account users account type.

Mail log:
Oct  8 06:51:06 Overlord postfix/postfix-script[3103261]: warning: not owned by root: /var/spool/postfix/etc/tokens/harryfoerster@outlook.com
Oct  8 06:51:06 Overlord postfix/postfix-script[3103306]: starting the Postfix mail system
Oct  8 06:51:06 Overlord postfix/master[3103308]: daemon started -- version 3.6.4, configuration /etc/postfix
Oct  8 06:53:40 Overlord postfix/pickup[3103309]: 09D42220B77: uid=0 from=<harryfoerster@outlook.com>
Oct  8 06:53:40 Overlord postfix/cleanup[3106331]: 09D42220B77: message-id=<20241008115340.09D42220B77@Overlord.wp.shawcable.net>
Oct  8 06:53:40 Overlord postfix/qmgr[3103310]: 09D42220B77: from=<harryfoerster@outlook.com>, size=416, nrcpt=1 (queue active)
Oct  8 06:53:41 Overlord postfix/smtp[3106333]: 09D42220B77: SASL authentication failed; cannot authenticate to server smtp.office365.com[52.96.223.50]: generic failure

Syslog:
Oct  8 06:51:05 Overlord systemd[1]: postfix@-.service: Deactivated successfully.
Oct  8 06:51:05 Overlord systemd[1]: Stopped Postfix Mail Transport Agent (instance -).
Oct  8 06:51:05 Overlord systemd[1]: postfix@-.service: Consumed 3min 11.532s CPU time.
Oct  8 06:51:05 Overlord systemd[1]: Starting Postfix Mail Transport Agent (instance -)...
Oct  8 06:51:06 Overlord systemd[1]: Started Postfix Mail Transport Agent (instance -).
Oct  8 06:51:06 Overlord systemd[1]: Starting Postfix Mail Transport Agent...
Oct  8 06:51:06 Overlord systemd[1]: Finished Postfix Mail Transport Agent.
Oct  8 06:53:41 Overlord sasl-xoauth2[3106333]: auth failed:

That is all the logging.

The instructions on SSL/TLS Certificates, I am unclear what is required here:
asl-xoauth2 also provides two configuration variables, ca_bundle_file and ca_certs_dir, that may be used to manually configure where the SSL/TLS libraries will look for a CA certificate bundle (for ca_bundle_file) or a set of CA certificates (for ca_certs_dir). Specify one or the other, but not both.

Where and how is ca_bundle_file or ca_certs_dir specified?

**Comment by b-mc** [comment]
I'm also running into a "generic error" on Ubuntu 24.04 (Noble):
```
2024-10-08T21:36:56.187073+02:00 hostname smtp: D135E7D161: to=<mail@outlook.com>, relay=smtp.office365.com[52.96.109.226]:587, delay=3107, delays=3107/0.14/0.64/0, dsn=4.7.0, status=deferred (SASL authentication failed; cannot authenticate to server smtp.office365.com[52.96.109.226]: generic failure)
2024-10-08T21:36:56.187491+02:00 hostname sasl-xoauth2: auth failed:
2024-10-08T21:36:56.187521+02:00 hostname sasl-xoauth2:   2024-10-08 21:36:56: Client: created
2024-10-08T21:36:56.187537+02:00 hostname sasl-xoauth2:   2024-10-08 21:36:56: Client::DoStep: called with state 0
2024-10-08T21:36:56.187571+02:00 hostname sasl-xoauth2:   2024-10-08 21:36:56: Client::InitialStep: TriggerAuthNameCallback err=0
2024-10-08T21:36:56.187589+02:00 hostname sasl-xoauth2:   2024-10-08 21:36:56: Client::InitialStep: TriggerPasswordCallback err=0
2024-10-08T21:36:56.187607+02:00 hostname sasl-xoauth2:   2024-10-08 21:36:56: TokenStore::Read: file=/var/spool/postfix/etc/tokens/oauth_token
2024-10-08T21:36:56.187622+02:00 hostname sasl-xoauth2:   2024-10-08 21:36:56: TokenStore::Read: failed to open file /var/spool/postfix/etc/tokens/oauth_token: No such file or directory
2024-10-08T21:36:56.187660+02:00 hostname sasl-xoauth2:   2024-10-08 21:36:56: Client::DoStep: new state 0 and err -1
2024-10-08T21:36:56.187678+02:00 hostname sasl-xoauth2:   2024-10-08 21:36:56: Client: destroyed
```

I'm currently scratching my head over why the file can't be accessed in chroot - I am certain that the path and permissions are OK, since the `postfix` user itself can access it just fine. Disabling chrooting for `smtp` and `smtpd` in `master.cf` fixes the issue, but I don't wanna leave it like that in the long run.

**Comment by tarickb** [comment]
@b-mc I think your issue is that you ought to specify just `/etc/tokens/oauth_token` in your `/etc/postfix/sasl_passwd` file. If that doesn't fix your problem please create a new issue here to avoid confusion with what @ClearlyDazed is reporting.

@ClearlyDazed can you try running `sasl-xoauth2-tool test-token-refresh`? There are some [instructions](https://github.com/tarickb/sasl-xoauth2/#testing-your-configuration) in the README.

**Comment by tarickb** [comment]
Going to assume this is fixed.
