### ISSUE TITLE
Token refresh failed

### ISSUE THREAD

**Issue by dremba** [tarickb/sasl-xoauth2#95]
Hello,

when I execute test-token-refresh, the refresh token fails. I don't know why token_endpoint https://accounts.google.com/o/oauth2/token is displayed because I use microsoft and have entered.

**test-token-refresh output:**

root@otrs:/home/otadmin# sasl-xoauth2-tool test-token-refresh /etc/tokens/test@mail.test.info
Config check passed.
auth failed:
  2024-10-07 10:31:57: TokenStore::Read: file=/etc/tokens/test@mail.test.info
  2024-10-07 10:31:57: TokenStore::Read: refresh=0.A5G..., user=
  2024-10-07 10:31:57: TokenStore::Refresh: attempt 1
  2024-10-07 10:31:57: TokenStore::Refresh: token_endpoint: https://accounts.google.com/o/oauth2/token
  2024-10-07 10:31:57: TokenStore::Refresh: request: client_id=CLIENT_ID_GOES_HERE&client_secret=CLIENT_SECRET_GOES_HERE&grant_type=refresh_token&refresh_token=0.ATEA...
  2024-10-07 10:31:57: TokenStore::Refresh: code=401, response={
  "error": "invalid_client",
  "error_description": "The OAuth client was not found."
}
  2024-10-07 10:31:57: TokenStore::Refresh: request failed
Token refresh failed.

**/etc/postfix/sasl_passwd:**
[smtp.office365.com]:587 test@mail.test.info:/etc/tokens/test@mail.test.info

**/etc/sasl-xoauth2.conf:**
{
  "client_id": "MY_CLIENT_ID",
  "client_secret": "",
  "token_endpoint": "https://login.microsoftonline.com/MY_TENANT_ID/oauth2/v2.0/token"
}

![image](https://github.com/user-attachments/assets/50da23c7-7719-46a9-ad07-969cc5c59c18)

![image](https://github.com/user-attachments/assets/b13324dc-1321-4723-9383-7c3c01903284)

Thank you for any help.

**Comment by tarickb** [comment]
Sorry for the dumb question but is it possible that you ran `sasl-xoauth2-tool test-token-refresh` before you set the token endpoint in `/etc/sasl-xoauth2.conf`?

**Comment by dremba** [comment]
Thanks for the quick response, no unfortunately not :D

**Comment by tarickb** [comment]
Do you have an endpoint override specified in `/etc/tokens/test@mail.test.info`?

**Comment by dremba** [comment]
Ah thank you, I have now added the token endpoint to the file /etc/tokens/test@mail.test.info. Now it takes the correct endpoint.

**Comment by nekku2** [comment]
Hi,
I have similar problem. Token refresh is not working, but with different error code. Should be token endpoint added to token file (_/etc/token/no-reply-token_) or _/etc/sasl-xoauth2.conf_ as below?

1. get token
```
sasl-xoauth2-tool get-token --client-id CLIENT-ID --tenant TENANT-ID --client-secret CLIENT-SECRET --use-device-flow outlook /etc/tokens/no-reply-token
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code GLBVT38BB to authenticate.
Acquired token.
```
2.  cat /etc/tokens/no-reply-token
```{
    "access_token": "eyJ0eX-XXX-0Q",
    "refresh_token": "1.ASEA-XXX-wunw",
    "expiry": 0
}
```
3. refresh token
```
sasl-xoauth2-tool test-token-refresh --config-file /etc/sasl-xoauth2.conf /etc/tokens/no-reply-token

Config check passed.
auth failed:
  2025-04-09 19:18:05: TokenStore::Read: file=/etc/tokens/no-reply-token
  2025-04-09 19:18:05: TokenStore::Read: refresh=1.ASEA-XXX-wunw, access=eyJ0eX-XXX-3S
  2025-04-09 19:18:05: TokenStore::Refresh: attempt 1
  2025-04-09 19:18:05: TokenStore::Refresh: token_endpoint: https://login.microsoftonline.com/TENANT-ID/oauth2/v2.0/token
  2025-04-09 19:18:05: TokenStore::Refresh: request: client_id=CLIENT-ID&client_secret=&grant_type=refresh_token&refresh_token=1.ASEA-XXX
  2025-04-09 19:18:05: TokenStore::Refresh: code=400, response={"error":"invalid_grant","error_description":"AADSTS70000: Provided grant is invalid or malformed. Trace ID: eb25ca15-57fe-4157-9295-318cbd893700 Correlation ID: 5aa2d0db-2ed9-4c5b-8410-a3e592ad4f4e Timestamp: 2025-04-09 17:18:05Z","error_codes":[70000],"timestamp":"2025-04-09 17:18:05Z","trace_id":"eb25ca15-57fe-4157-9295-318cbd893700","correlation_id":"5aa2d0db-2ed9-4c5b-8410-a3e592ad4f4e","error_uri":"https://login.microsoftonline.com/error?code=70000"}
  2025-04-09 19:18:05: TokenStore::Refresh: request failed
Token refresh failed.

```

 TokenStore::Refresh: code=400, response={"error":"invalid_grant","error_description":"AADSTS70000: Provided grant is invalid or malformed. 

4. cat /etc/sasl-xoauth2.conf
```
{
  "client_id": "CLIENT-ID",
  "client_secret": "",
  "token_endpoint": "https://login.microsoftonline.com/TENANT-ID/oauth2/v2.0/token",
  "log_to_syslog_on_failure": "yes",
  "log_full_trace_on_failure": "yes"
}

```

**Comment by tarickb** [comment]
Your invocation of `sasl-xoauth2-tool get-token` specifies a client secret, but your `/etc/sasl-xoauth2.conf` doesn't contain a secret. It's unclear if this is just a redaction thing or not, but if you specify a secret to get the token, you have to put that secret into `/etc/sasl-xoauth2.conf` too.

**Comment by nekku2** [comment]
There is no difference betweeen 2 options:
1. `/etc/sasl-xoauth2.conf` contain _client_secret_ value and get-token command is:
`sasl-xoauth2-tool get-token --client-id CLIENT-ID --tenant TENANT-ID --client-secret CLIENT-SECRET --use-device-flow outlook /etc/tokens/no-reply-token`
2. `/etc/sasl-xoauth2.conf`  _client_secret_  is empty ( "" ) and get-token command is:
`sasl-xoauth2-tool get-token --client-id CLIENT-ID --tenant TENANT-ID --use-device-flow outlook /etc/tokens/no-reply-token`

Token is acquired in both cases, but not refreshed. 

Refresh command (the same for both):
`sasl-xoauth2-tool test-token-refresh --config-file /etc/sasl-xoauth2.conf /etc/tokens/no-reply-token`

Error is the same:
_TokenStore::Refresh: code=400, response={"error":"invalid_grant","error_description":"AADSTS70000: Provided grant is invalid or malformed._

EntraID sign-in log shows the same error:
![Image](https://github.com/user-attachments/assets/ce3fd677-75ca-4140-9070-26046cf59b18)

sasl-xoauth2 is installed from epel:
`sasl-xoauth2.x86_64 0.24-1.el9`
OS is Rocky 9.5.

I can try different OS - what do you suggest?

**Comment by tarickb** [comment]
Yeah I don't know -- these Microsoft errors are pretty inscrutable to me. Maybe you're passing in the wrong client ID? Maybe the wrong tenant ID? Maybe review the [setup instructions](https://github.com/tarickb/sasl-xoauth2/?tab=readme-ov-file#outlookoffice-365-configuration-device-flow) for device-flow clients to make sure you didn't skip a step?

**Comment by nekku2** [comment]
Finally, I rebuilt config again and it's working for M365 tenant :)
Probably something with entra app or app-id, I'm not sure. Summary below:

1. App permissions: 
![Image](https://github.com/user-attachments/assets/3c8b9bb8-ac7f-46f8-8ec0-09ee0f3c9f2d)

2. cat /etc/sasl-xoauth2.conf
```
{
  "client_id": "[paste CLIENT-ID here]",
  "client_secret": "",
  "token_endpoint": "https://login.microsoftonline.com/[paste TENANT ID here]/oauth2/v2.0/token"
}
```

3. On Rocky 9.5 or 8.10 there was need to properly install _python msal_ module and update python modules
`pip install msal`

4. Get token with command:
`sasl-xoauth2-tool get-token --client-id [paste CLIENT-ID here] --tenant [paste TENANT ID here] --use-device-flow outlook /etc/tokens/mail@my.domain.com`

After authentication via browser token is aquired

![Image](https://github.com/user-attachments/assets/d2c8e858-b330-4af9-8637-172c4e1fc6f4)

5. Refresh token to verify if it works with command:
`sasl-xoauth2-tool test-token-refresh --config-file /etc/sasl-xoauth2.conf /etc/tokens/mail@my.domain.com`
Result:
![Image](https://github.com/user-attachments/assets/75beda09-d88d-4168-a070-25a6a3e1087d)

6. Configure _/etc/postfix/sasl_passwd_
`[smtp.office365.com]:587 mail@my.domain.com:/etc/tokens/mail@my.domain.com`

8. Configure postfix to relay to M365 and use /etc/postfix/sasl_passwd
```
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
smtp_sasl_security_options =
smtp_sasl_mechanism_filter = xoauth2
relayhost = [smtp.office365.com]:587
```

Finally configured account can be used as sender. Shared mailboxes (with SendAs permissions for mail@my.domain.com) also can be used.

@tarickb thanks for your support and fast response :)

**Comment by tarickb** [comment]
That's great, glad you got it figured out!
